JWT with RS256
shawnzhu/artifacts-v2 pull request #10
Opened 2016-12-06 22:24 UTC by shawnzhu

fixes #8 

It introduces one configuration option to specify a public key file path via environment variable `JWT_PUBLIC_KEY_PATH`

2016-12-06 22:39 UTC, meatballhat requested changes

2016-12-06 22:39 UTC, meatballhat commented on router/jwt.go
> +	publicKeyPEM, _ := ioutil.ReadFile(os.Getenv("JWT_PUBLIC_KEY_PATH"))
I would prefer these to be strings read directly from the env.  We typically deploy via Heroku and Docker, injecting configuration entirely via the env, and making no assumptions about file access.

2016-12-06 22:39 UTC, meatballhat commented on router/route.go
> +	var router = gin.Default()
I realize this may be a little late, but are you OK with using gorilla mux for routing instead?

2016-12-06 22:39 UTC, meatballhat commented on router/route.go
> +	var router = gin.Default()
I also prefer negroni for middleware handling 😐 .  Sorry to be so specific.   If you feel strongly about sticking with gin, then I'll roll with it.

2016-12-07 02:38 UTC, shawnzhu commented on router/jwt.go
> +	publicKeyPEM, _ := ioutil.ReadFile(os.Getenv("JWT_PUBLIC_KEY_PATH"))
Yes, that's what I'm going to do next since I will have the same problem when deploying it.

2016-12-07 02:43 UTC, shawnzhu commented on router/route.go
> +	var router = gin.Default()
No problem. but I will make it in another PR

2016-12-07 04:28 UTC, meatballhat approved these changes
👏 🎉

2016-12-07 15:23 UTC, merged